language: java
jdk:
  - oraclejdk8
branches:
  only:
    - master
script: mvn -f chapter-8/build/pom.xml verify
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
after_success:
  - mvn -f chapter-8/build/pom.xml test jacoco:report coveralls:report